mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.urls import include, path
from users import views as user_views

urlpatterns = [
    path('register/', user_views.register, name='user_register'),
    path('profile/', user_views.profile, name='user_profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/user_login.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/user_logout.html'), name='user_logout'),
    path('school/', include('school.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='school/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/school/urls.py
from django.urls import path
from . import views


app_name = "school"


urlpatterns = [
    path('', views.SchoolMainView.as_view(), name='school_main'),

    path('teacher', views.TeacherGeneralView.as_view(), name='teacher_general'),
    path('teacher/<int:pk>', views.TeacherDetailView.as_view(), name='teacher_detail'),

    path('student', views.StudentGeneralView.as_view(), name='student_general'),
    path('student/<int:pk>', views.StudentDetailView.as_view(), name='student_detail'),

    path('anno', views.AnnoGeneralView.as_view(), name='anno_general'),
    path('anno/<int:pk>', views.AnnoDetailView.as_view(), name='anno_detail'),
    path('anno/create', views.AnnoCreateView.as_view(), name='anno_create'),
    path('anno/<int:pk>/update', views.AnnoUpdateView.as_view(), name='anno_update'),
    path('anno/<int:pk>/delete', views.AnnoDeleteView.as_view(), name='anno_delete'),

    path('admin/register', views.AdminRegisterListView.as_view(), name='register_general'),
    path('admin/register/<int:pk>', views.AdminRegisterUpdateView.as_view(), name='register_update'),

    path('test/<int:pk>', views.TestClassView.as_view(), name='test_detail'),
]


mysite/school/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.urls import reverse
from users.models import User
from . import validators as val


class SchoolUser(models.Model):
    class TypeTeacherStudent(models.TextChoices):
        STUDENT = 'S', ("Student")
        TEACHER = 'T', ("Teacher")
        ADMIN = 'A', ("Admin")
        UNDETERMINED = 'U', ("Undetermined")

    site_user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=False,
        help_text="User of school website",
    )

    type_user = models.CharField(
        max_length=1,
        choices=TypeTeacherStudent.choices,
        default=TypeTeacherStudent.STUDENT,
        help_text="Type of user(Teacher, Student, Admin, Undetermined)",
    )

    def __str__(self):
        return f"\nPrimary Key: {self.pk}\nUser Type: {self.type_user}\nUsername: {self.site_user.username}\n"
    
    def get_absolute_url(self):
        return reverse('school:register_general')


class Teacher(models.Model):
    teacher_user = models.OneToOneField(
        SchoolUser,
        on_delete=models.CASCADE,
        null=False,
        help_text="Teacher user",
    )

    def __str__(self):
        return f"\nPrimery Key: {self.pk}\nUsername: {self.teacher_user.site_user.username}\n"
    
    def clean(self):
        if self.teacher_user.type_user != 'T':
            raise ValidationError(
                ('%(value)s is not a teacher(Value: %(type_user)s)'),
                params={'value': self.teacher_user.site_user.username, 'type_user': self.teacher_user.type_user},
            )


class Student(models.Model):
    student_user = models.OneToOneField(
        SchoolUser,
        on_delete=models.CASCADE,
        null=False,
        help_text="Student user",
    )

    advisor_teacher = models.ForeignKey(
        Teacher,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="Teacher that advises the student",
    )

    def __str__(self):
        return f"\nPrimery Key: {self.pk}\nUsername: {self.student_user.site_user.username}\n"
    
    def clean(self):
        if self.student_user.type_user != 'S':
            raise ValidationError(
                ('%(value)s is not a student(Value: %(type_user)s)'),
                params={'value': self.student_user.site_user.username, 'type_user': self.student_user.type_user},
            )


class Announcement(models.Model):
    anno_title = models.CharField(
        max_length=100,
        help_text="Title of announcement",
    )

    anno_content = models.TextField(
        help_text="Content of announcement",
    )
    
    anno_date = models.DateTimeField(
        default=timezone.now,
        help_text="Date of creation",
    )

    auther_name = models.ForeignKey(
        SchoolUser,
        on_delete=models.CASCADE,
        help_text="Name of auther",
    )

    def __str__(self):
        return f"\nPrimary Key: {self.pk}\nTitle: {self.anno_title}\nCreation Date: {self.anno_date}\n"

    def get_absolute_url(self):
        return reverse('school:anno_detail', kwargs={'pk': self.pk})


class Subject(models.Model):
    subject_name = models.CharField(
        max_length=100,
        help_text="Name of subject",
    )

    def __str__(self):
        return f"\nPrimary Key: {self.pk}\nSubject: {self.subject_name}"


class SchoolClass(models.Model):
    class_subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE,
        help_text="Subject the class is based on",
    )

    class_time = models.IntegerField(
        validators=[val.check_schoolclass_semester_valid],
        help_text="Year + semester of the subject",
    )

    assigned_teacher = models.ForeignKey(
        Teacher,
        on_delete=models.CASCADE,
        help_text="Teacher teaching class",
    )

    def __str__(self):
        return f"\nPrimery Key: {self.pk}\nClass Time: {self.class_time}\nAssigned Teacher: {self.assigned_teacher.teacher_user.site_user.username}\n"


class ClassStudentRelation(models.Model):
    class_relate = models.ForeignKey(
        SchoolClass,
        on_delete=models.CASCADE,
        help_text="Connected class to student",
    )

    student_relate = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        help_text="Connected student to class",
    )

    def __str__(self):
        return f"\nPrimery Key: {self.pk}\nClass Subject: {self.class_relate.class_subject}\nClass Time: {self.class_relate.class_time}\nAssigned Teacher: {self.class_relate.assigned_teacher.teacher_user.site_user.username}\nStudent: {self.student_relate.student_user.site_user.username}\n"

mysite/school/forms.py
from django import forms
from .models import Announcement


class AnnoCreateForm(forms.Form):
    class Meta:
        model = Announcement
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

mysite/school/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import AnonymousUser
from .models import SchoolUser, Teacher, Student, Announcement
from .forms import AnnoCreateForm


def get_context_schooluser(user, context):
    is_admin = False
    is_teacher = False
    is_student = False
    is_undetermined = False
    if not isinstance(user, AnonymousUser):
        try:
            temp_user = SchoolUser.objects.get(site_user=user)
        except SchoolUser.DoesNotExist:
            auto_create_undetermined_schooluser(user, 'U')
            is_undetermined = True
        else:
            if temp_user.type_user == 'A':
                is_admin = True
            elif temp_user.type_user == 'T':
                is_teacher = True
            elif temp_user.type_user == 'S':
                is_student = True
            else:
                is_undetermined = True
    else:
        is_undetermined = True

    context['is_admin'] = is_admin
    context['is_teacher'] = is_teacher
    context['is_student'] = is_student
    context['is_undetermined'] = is_undetermined

    return


def auto_create_undetermined_schooluser(user, user_type):
    SchoolUser.objects.create(site_user=user, type_user=user_type)


# region Announcement

class AnnoDetailView(generic.DetailView):
    model = Announcement
    template_name = 'school/anno_detail.html'
    context_object_name = 'anno'

    def get_context_data(self, **kwargs):
        context = super(AnnoDetailView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

class AnnoCreateView(LoginRequiredMixin, generic.CreateView):
    model = Announcement
    template_name = 'school/anno_create.html'
    fields = ['anno_title', 'anno_content']
    login_url = '/login/'

    def form_valid(self, form):
        form.instance.auther_name = SchoolUser.objects.get(site_user=self.request.user)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AnnoCreateView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

class AnnoUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Announcement
    template_name = 'school/anno_update.html'
    fields = ['anno_title', 'anno_content']
    login_url = '/login/'

    def form_valid(self, form):
        form.instance.auther_name.site_user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        anno = self.get_object()
        if self.request.user == anno.auther_name.site_user or SchoolUser.objects.get(site_user=self.request.user).type_user == 'A':
            return True
        return False
    
    def get_context_data(self, **kwargs):
        context = super(AnnoUpdateView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

class AnnoDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Announcement
    template_name = 'school/anno_delete.html'
    context_object_name = 'anno'
    success_url = '/school/anno'
    login_url = '/login/'

    def test_func(self):
        anno = self.get_object()
        if self.request.user == anno.auther_name.site_user or SchoolUser.objects.get(site_user=self.request.user).type_user == 'A':
            return True
        return False
    
    def get_context_data(self, **kwargs):
        context = super(AnnoDeleteView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

class AnnoGeneralView(generic.ListView):
    model = Announcement
    template_name = 'school/anno_generic.html'
    context_object_name = 'anno_list'

    def get_queryset(self):
        return Announcement.objects.all()

    def get_context_data(self, **kwargs):
        context = super(AnnoGeneralView, self).get_context_data(**kwargs)

        get_context_schooluser(self.request.user, context)
        
        return context

# endregion


# region Teacher

class TeacherGeneralView(generic.ListView):
    model = Teacher
    template_name = 'school/teacher_generic.html'
    context_object_name = 'teacher_list'

    def get_queryset(self):
        return Teacher.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(TeacherGeneralView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

class TeacherDetailView(generic.DetailView):
    model = Teacher
    template_name = 'school/teacher_detail.html'
    context_object_name = 'teacher'

    def get_context_data(self, **kwargs):
        context = super(TeacherDetailView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

# endregion


# region Student

class StudentGeneralView(generic.ListView):
    model = Student
    template_name = 'school/student_generic.html'
    context_object_name = 'student_list'

    def get_queryset(self):
        return Student.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(StudentGeneralView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

class StudentDetailView(generic.DetailView):
    model = Student
    template_name = 'school/student_detail.html'
    context_object_name = 'student'

    def get_context_data(self, **kwargs):
        context = super(StudentDetailView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

# endregion


# region Admin

class AdminRegisterListView(LoginRequiredMixin, generic.ListView):
    model = SchoolUser
    template_name = 'school/register_generic.html'
    context_object_name = 'register_list'
    login_url = '/login/'

    def get_queryset(self):
        return SchoolUser.objects.filter(type_user='U')
    
    def get_context_data(self, **kwargs):
        context = super(AdminRegisterListView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

class AdminRegisterUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = SchoolUser
    template_name = 'school/register_update.html'
    context_object_name = 'schooluser'
    fields = ['type_user']
    login_url = '/login/'

    def form_valid(self, form):
        if form.instance.type_user == 'S':
            if not Student.objects.filter(student_user=form.instance):
                temp = Student(student_user=form.instance)
                temp.save()
        elif form.instance.type_user == 'T':
            if not Teacher.objects.filter(teacher_user=form.instance):
                temp = Teacher(teacher_user=form.instance)
                temp.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(AdminRegisterUpdateView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context

# endregion


class SchoolMainView(generic.ListView):
    template_name = 'school/main_page.html'
    model = Announcement
    context_object_name = 'announcement_list'
    ordering = ['-date_posted']

    def get_queryset(self):
        return Announcement.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(SchoolMainView, self).get_context_data(**kwargs)
        
        get_context_schooluser(self.request.user, context)
        
        return context


class TestClassView(generic.DetailView):
    model = Teacher
    template_name = 'school/test.html'

mysite/school/templates/school/anno_create.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% if is_teacher or is_admin %}
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        Blog Post
                    </legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">
                        Post
                    </button>
                </div>
            </form>
        </div>
    {% else %}
        <div class="content-section">
            <p>You are not a teacher or admin</p>
        </div>
    {% endif %}
{% endblock %}

mysite/school/templates/school/anno_delete.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Delete Post
                </legend>
                <h2>
                    Are you sure you want to delete the post {{ anno.anno_title }}
                </h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">
                    Delete
                </button>
                <a class="btn btn-outline-secondary" href="{% url 'school:anno_detail' anno.id %}">
                    Cancel
                </a>
            </div>
        </form>
    </div>
{% endblock %}

mysite/school/templates/school/anno_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <article class="media content-section">
        <img class="rounded-circle aritcle-img" src="{{ anno.auther_name.site_user.profile.image.url }}" width="100" height="100">
        <div class="media-body">
            <h2 class="ml-2 article-title">{{ anno.anno_title }}</h2>
            <div class="article-metadata">
                <a class="ml-2 mr-2" href="#">{{ anno.auther_name.site_user }}</a>
                <small class="text-muted">{{ anno.anno_date|date:"F d, Y" }}</small>
                {% if anno.auther_name.site_user == user or is_admin %}
                    <div>
                        <a class="ml-2 btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'school:anno_update' object.id %}">Update</a>
                        <a class="ml-2 btn btn-danger btn-sm mt-1 mb-1" href="{% url 'school:anno_delete' object.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
        <p class="article-content">{{ anno.anno_content }}</p>
        </div>
    </article>
{% endblock %}

mysite/school/templates/school/anno_generic.html
{% extends "base_generic.html" %}

{% block content %}
    {% if is_admin or is_teacher %}
        <div class="media-body">
            <a class="nav-item nav-link" href="{% url 'school:anno_create' %}">
                <button class="btn btn-outline-info" type="submit">
                    Create new announcement
                </button>
            </a>
        </div>
    {% endif %}
    {% for anno in anno_list %}
        <article class="media content-section">
            <img class="rounded-circle aritcle-img" src="{{ anno.auther_name.site_user.profile.image.url }}" width="100" height="100">
            <div class="media-body">
            <div class="article-metadata">
              <a class="ml-2 mr-2" href="#">{{ anno.auther_name.site_user }}</a>
              <small class="text-muted">{{ anno.anno_date|date:"F d, Y" }}</small>
            </div>
            <h2><a class="ml-2 article-title" href="{% url 'school:anno_detail' anno.id %}">{{ anno.anno_title }}</a></h2>
            <p class="ml-2 article-content">{{ anno.anno_content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock %}

mysite/school/templates/school/anno_update.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Blog Post
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                    Post
                </button>
            </div>
        </form>
    </div>
{% endblock %}

mysite/school/templates/school/main_page.html
{% extends "base_generic.html" %}


mysite/school/templates/school/register_generic.html
{% extends "base_generic.html" %}

{% block content %}
    {% if is_admin %}
        <p>This is the register generic page</p>
        
        <ul>
            {% for register in register_list %}
                <li><a class="article-title" href="{% url 'school:register_update' register.id %}">{{ register }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Only admins can access this page</p>
    {% endif %}
{% endblock %}

mysite/school/templates/school/register_update.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% if is_admin %}
        <div class="content-section">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        User Update
                    </legend>
                    <p>First Name: {{ schooluser.site_user.first_name }}</p>
                    <p>Last Name: {{ schooluser.site_user.last_name }}</p>
                    <p>Username: {{ schooluser.site_user.username }}</p>
                    <p>Registerd Date: {{ schooluser.site_user.date_joined }}</p>
                    <p>E-Mail: {{ schooluser.site_user.email }}</p>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">
                        Update User
                    </button>
                </div>
            </form>
        </div>
    {% else %}
        <p>Only admins can access this page</p>
    {% endif %}
{% endblock %}

mysite/school/templates/school/student_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.user_profile.image.url }}">
            <div class="media-body">
              <h2 class="account-heading">{{ student.student_user.site_user.username }}</h2>
              <p class="text-secondary">{{ student.student_user.site_user.email }}</p>
            </div>
          </div>
        <p>This is the student detail page</p>
        <p>First Name: {{ student.student_user.site_user.first_name }}</p>
        <p>Last Name: {{ student.student_user.site_user.last_name }}</p>
        <p>Register Date: {{ student.student_user.site_user.date_joined }}</p>
        {% if student.advisor_teacher %}
            <p>Advisor: <a href="{% url 'school:teacher_detail' student.advisor_teacher.id %}">{{ student.advisor_teacher.teacher_user.username }}</a></p>
        {% else %}
            <p>No Advisor detected: Check with school to update</p>
        {% endif %}
    </div>
{% endblock %}

mysite/school/templates/school/student_generic.html
{% extends "base_generic.html" %}

{% block content %}
    <p>This is the student generic page</p>
    
    <ul>
        {% for student in student_list %}
            <li><a href="{% url 'school:student_detail' student.id %}">{{ student.student_user.site_user.username }}({{ student.student_user.site_user.last_name }})</a></li>
        {% endfor %}
    </ul>
{% endblock %}

mysite/school/templates/school/teacher_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <p>This is the teacher detail page</p>
    <p>Username: {{ teacher.teacher_user.site_user.username }}</p>
    <p>First Name: {{ teacher.teacher_user.site_user.first_name }}</p>
    <p>Last Name: {{ teacher.teacher_user.site_user.last_name }}</p>
    <p>Username: {{ teacher.teacher_user.site_user.username }}</p>
{% endblock %}

mysite/school/templates/school/teacher_generic.html
{% extends "base_generic.html" %}

{% block content %}
    <p>This is the teacher generic page</p>

    <ul>
        {% for teacher in teacher_list %}
            <li><a href="{% url 'school:teacher_detail' teacher.id %}">{{ teacher.teacher_user.site_user.username }}({{ teacher.teacher_user.site_user.first_name }})</a></li>
        {% endfor %}
    </ul>
{% endblock %}

mysite/school/templates/school/test.html
{% extends "base_generic.html" %}

{% block content %}
    <p>This is the teacher detail page</p>
    <p>Username: {{ teacher.teacher_user.username }}</p>
{% endblock %}